/**
 * Skills the built-in matcher recognises. The first name is how a skill is shown; the rest
 * are spellings that count as the same skill. Matching is case-insensitive on whole words.
 * Add entries freely — this list is the main lever for match quality without an AI model.
 */
export const SKILLS: readonly (readonly string[])[] = [
  // Languages
  ['JavaScript', 'javascript', 'js', 'ecmascript', 'es6'],
  ['TypeScript', 'typescript', 'ts'],
  ['Python', 'python'],
  ['Java', 'java'],
  ['Kotlin', 'kotlin'],
  ['Scala', 'scala'],
  ['Go', 'golang', 'go lang'],
  ['Rust', 'rust'],
  ['C', 'ansi c', 'c programming'],
  ['C++', 'c++', 'cpp'],
  ['C#', 'c#', 'csharp', 'c sharp'],
  ['PHP', 'php'],
  ['Ruby', 'ruby'],
  ['Swift', 'swift'],
  ['Objective-C', 'objective-c', 'objective c'],
  ['Dart', 'dart'],
  ['Elixir', 'elixir'],
  ['Haskell', 'haskell'],
  ['R', 'r programming', 'r language', 'rstudio'],
  ['MATLAB', 'matlab'],
  ['Perl', 'perl'],
  ['Bash', 'bash', 'shell scripting', 'shell script'],
  ['PowerShell', 'powershell'],
  ['SQL', 'sql'],
  ['GraphQL', 'graphql'],
  ['HTML', 'html', 'html5'],
  ['CSS', 'css', 'css3'],
  ['Sass', 'sass', 'scss'],
  // Frontend
  ['React', 'react', 'react.js', 'reactjs'],
  ['Next.js', 'next.js', 'nextjs'],
  ['Vue', 'vue', 'vue.js', 'vuejs'],
  ['Nuxt', 'nuxt', 'nuxt.js'],
  ['Angular', 'angular', 'angularjs'],
  ['Svelte', 'svelte', 'sveltekit'],
  ['Redux', 'redux'],
  ['Tailwind CSS', 'tailwind', 'tailwindcss', 'tailwind css'],
  ['React Native', 'react native', 'react-native'],
  ['Flutter', 'flutter'],
  ['jQuery', 'jquery'],
  ['Webpack', 'webpack'],
  ['Vite', 'vite'],
  ['Accessibility', 'accessibility', 'a11y', 'wcag'],
  // Backend
  ['Node.js', 'node.js', 'nodejs', 'node'],
  ['Express', 'express.js', 'expressjs'],
  ['NestJS', 'nestjs', 'nest.js'],
  ['Django', 'django'],
  ['Flask', 'flask'],
  ['FastAPI', 'fastapi'],
  ['Spring', 'spring boot', 'springboot', 'spring framework'],
  ['Ruby on Rails', 'rails', 'ruby on rails'],
  ['Laravel', 'laravel'],
  ['.NET', '.net', 'dotnet', 'asp.net', '.net core'],
  ['REST APIs', 'restful', 'rest api', 'rest apis'],
  ['gRPC', 'grpc'],
  ['Microservices', 'microservices', 'microservice'],
  ['WebSockets', 'websocket', 'websockets'],
  ['Kafka', 'kafka'],
  ['RabbitMQ', 'rabbitmq'],
  ['Redis', 'redis'],
  ['Elasticsearch', 'elasticsearch', 'elastic search', 'opensearch'],
  // Data stores
  ['PostgreSQL', 'postgresql', 'postgres'],
  ['MySQL', 'mysql', 'mariadb'],
  ['MongoDB', 'mongodb', 'mongo'],
  ['SQLite', 'sqlite'],
  ['DynamoDB', 'dynamodb'],
  ['Cassandra', 'cassandra'],
  ['Oracle Database', 'oracle'],
  ['SQL Server', 'sql server', 'mssql'],
  ['Prisma', 'prisma'],
  ['Snowflake', 'snowflake'],
  ['BigQuery', 'bigquery'],
  // Cloud & DevOps
  ['AWS', 'aws', 'amazon web services'],
  ['Azure', 'azure'],
  ['Google Cloud', 'gcp', 'google cloud'],
  ['Docker', 'docker', 'containers', 'containerization'],
  ['Kubernetes', 'kubernetes', 'k8s'],
  ['Terraform', 'terraform'],
  ['Ansible', 'ansible'],
  [
    'CI/CD',
    'ci/cd',
    'ci',
    'continuous integration',
    'continuous delivery',
    'continuous deployment',
  ],
  ['GitHub Actions', 'github actions'],
  ['Jenkins', 'jenkins'],
  ['Git', 'git', 'github', 'gitlab', 'bitbucket'],
  ['Linux', 'linux', 'unix'],
  ['Nginx', 'nginx'],
  ['Serverless', 'serverless', 'lambda', 'cloud functions'],
  ['Monitoring', 'monitoring', 'observability', 'prometheus', 'grafana', 'datadog'],
  ['Security', 'security', 'owasp', 'application security'],
  // Data & ML
  ['Machine learning', 'machine learning', 'ml'],
  ['Deep learning', 'deep learning'],
  ['NLP', 'nlp', 'natural language processing'],
  ['LLMs', 'llm', 'llms', 'large language models', 'generative ai', 'genai'],
  ['PyTorch', 'pytorch'],
  ['TensorFlow', 'tensorflow'],
  ['scikit-learn', 'scikit-learn', 'sklearn'],
  ['Pandas', 'pandas'],
  ['NumPy', 'numpy'],
  ['Spark', 'spark', 'pyspark', 'apache spark'],
  ['Airflow', 'airflow'],
  ['dbt', 'dbt'],
  ['ETL', 'etl', 'elt', 'data pipelines', 'data pipeline'],
  ['Data analysis', 'data analysis', 'data analytics', 'analytics'],
  ['Data visualization', 'data visualization', 'data visualisation', 'dashboards'],
  ['Statistics', 'statistics', 'statistical'],
  ['Excel', 'microsoft excel', 'ms excel', 'spreadsheets'],
  ['Tableau', 'tableau'],
  ['Power BI', 'power bi', 'powerbi'],
  // Testing & quality
  ['Unit testing', 'unit testing', 'unit tests'],
  ['Test automation', 'test automation', 'automated testing', 'automation testing'],
  ['Jest', 'jest'],
  ['Vitest', 'vitest'],
  ['Cypress', 'cypress'],
  ['Playwright', 'playwright'],
  ['Selenium', 'selenium'],
  ['TDD', 'tdd', 'test-driven development', 'test driven development'],
  ['Code review', 'code review', 'code reviews'],
  // Mobile
  ['iOS', 'ios'],
  ['Android', 'android'],
  // Design & product
  ['Figma', 'figma'],
  ['UI design', 'ui design', 'user interface design'],
  ['UX', 'ux', 'user experience', 'ux research'],
  ['Product management', 'product management', 'product manager'],
  ['SEO', 'seo', 'search engine optimization'],
  ['Digital marketing', 'digital marketing'],
  ['Content writing', 'content writing', 'copywriting'],
  ['Salesforce', 'salesforce'],
  ['CRM', 'crm'],
  ['SAP', 'sap'],
  // Ways of working
  ['Agile', 'agile', 'scrum', 'kanban'],
  ['Jira', 'jira'],
  ['System design', 'system design', 'distributed systems', 'scalability'],
  ['API design', 'api design'],
  ['Performance optimization', 'performance optimization', 'performance tuning'],
  ['Leadership', 'leadership', 'team lead', 'tech lead', 'led a team', 'leading teams'],
  ['Mentoring', 'mentoring', 'mentorship', 'mentor', 'coaching'],
  ['Communication', 'communication', 'communication skills'],
  ['Stakeholder management', 'stakeholder management', 'stakeholders'],
  ['Project management', 'project management'],
  ['Problem solving', 'problem solving', 'problem-solving'],
  ['Customer service', 'customer service', 'customer support'],
];
